name: init-django

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  init_django:
    runs-on: windows-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.2

      - name: Create Django project
        run: |
          pip install virtualenv
          mkdir example
          cd example
          virtualenv venv
          start venv\Scripts\activate
          pip install django
          django-admin startproject example
          cd ..

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: project
          path: example
